apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wordpresses.dynamic.microowl.com
spec:
  group: dynamic.microowl.com
  version: v1
  names:
    kind: Website
    plural: Websites
  scope: Namespaced
