apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wordpress-operator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: websites.dynamic.microowl.com
  annotations:
    composition: Deployment, Service
spec:
  group: dynamic.microowl.com
  version: v1
  names:
    kind: Website
    plural: websites
  scope: Namespaced
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-operator-deployment
  labels:
    app: wordpress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-operator
  template:
    metadata:
      labels:
        app: wordpress-operator
    spec:
      containers:
        - name: wordpress-operator
          image: wordpress-operator:v1alpha1
          imagePullPolicy: IfNotPresent
          command: ["/wordpress-operator"]
